/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
/**
 *
 * @author tanar
 */
public class ZooForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ZooForm.class.getName());

    /**
     * Creates new form ZooForm
     */
    public ZooForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        northPnl = new javax.swing.JPanel();
        infoLbl = new javax.swing.JLabel();
        eastPnl = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        loadBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        modBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        delBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        southPnl = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        statusLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        westPnl = new javax.swing.JPanel();
        centerPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        zooTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setLayout(new java.awt.BorderLayout());

        northPnl.setAlignmentY(15.0F);
        northPnl.setPreferredSize(new java.awt.Dimension(957, 40));

        infoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLbl.setText("jLabel1");
        infoLbl.setPreferredSize(new java.awt.Dimension(42, 35));
        northPnl.add(infoLbl);

        jPanel1.add(northPnl, java.awt.BorderLayout.NORTH);

        eastPnl.setPreferredSize(new java.awt.Dimension(150, 581));
        eastPnl.setLayout(new java.awt.GridLayout(8, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        eastPnl.add(jPanel5);

        loadBtn.setText("Betöltés");
        loadBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel6.add(loadBtn);

        eastPnl.add(jPanel6);

        saveBtn.setText("Mentés");
        saveBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel7.add(saveBtn);

        eastPnl.add(jPanel7);

        modBtn.setText("Módosítás");
        modBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel8.add(modBtn);

        eastPnl.add(jPanel8);

        delBtn.setText("Törlés");
        delBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel9.add(delBtn);

        eastPnl.add(jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        eastPnl.add(jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        eastPnl.add(jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        eastPnl.add(jPanel12);

        jPanel1.add(eastPnl, java.awt.BorderLayout.EAST);

        southPnl.setPreferredSize(new java.awt.Dimension(957, 50));
        southPnl.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        southPnl.add(jPanel2);

        statusLbl.setText("jLabel1");
        statusLbl.setPreferredSize(new java.awt.Dimension(42, 35));
        jPanel3.add(statusLbl);

        southPnl.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 0));

        exitBtn.setText("Kilépés");
        exitBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel4.add(exitBtn);

        southPnl.add(jPanel4);

        jPanel1.add(southPnl, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout westPnlLayout = new javax.swing.GroupLayout(westPnl);
        westPnl.setLayout(westPnlLayout);
        westPnlLayout.setHorizontalGroup(
            westPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        westPnlLayout.setVerticalGroup(
            westPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        jPanel1.add(westPnl, java.awt.BorderLayout.WEST);

        centerPnl.setLayout(new java.awt.GridLayout(1, 1));

        zooTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(zooTbl);

        centerPnl.add(jScrollPane1);

        jPanel1.add(centerPnl, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ZooForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPnl;
    private javax.swing.JButton delBtn;
    private javax.swing.JPanel eastPnl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton modBtn;
    private javax.swing.JPanel northPnl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel southPnl;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JPanel westPnl;
    private javax.swing.JTable zooTbl;
    // End of variables declaration//GEN-END:variables

    public JButton getDelBtn() {
        return delBtn;
    }

    public JButton getExitBtn() {
        return exitBtn;
    }

    public JButton getModBtn() {
        return modBtn;
    }

    public JButton getSaveBtn() {
        return saveBtn;
    }

    public JTable getZooTbl() {
        return zooTbl;
    }

    public JButton getLoadBtn() {
        return loadBtn;
    }
    

    public void setStatusLbl( String text ) {
        
        statusLbl.setText( text );
    }

    public void setInfoLbl( String text ) {
        
        infoLbl.setText( text );
    }

    
}
